server:
  port: 8020
spring:
  application:
    name: my-consumer-server
  rabbitmq:
    host: 114.116.106.172
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        retry:
          enable: true # 开启消费者失败重试
          initial-interval: 1000
          multiplier: 1
          max-attempts: 3
          stateless: true
#  zipkin:
#    base-url: http://114.116.106.172:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1.0
  cloud:
    nacos:
      discovery:  #使用注册中心
        server-addr: 114.116.106.172:8848 #Nacos访问地址
        cluster-name: HB
#eureka:
#  client:
#    service-url:
#      defaultZone: http://114.116.106.172:7001/eureka/
#    enabled: true
#  instance:
#    prefer-ip-address: true