server:
  port: 8029
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 114.116.106.172:8848
    gateway:
      routes:
        - id: consumer-server
          uri: lb://my-consumer-server
          predicates:
            - Path=/human/remote/**
      globalcors: # 跨域
        cors-configurations:
          #仅在开发环境设置为*
          '[ /**] ':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
  main:
    web-application-type: reactive

