server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://114.116.106.172:3306/cgdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liulang
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    lettuce:
      pool:
        max-active: 8
        max-wait: 10s
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 1s
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 114.116.106.172
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        output-out-0:
          destination: demoExchange
          contentType: application/json
    nacos:
      discovery:  #使用注册中心
        server-addr: 114.116.106.172:8848 #Nacos访问地址
        enabled: true
      config:
        server-addr: 114.116.106.172:8848   #配置中心地址
        file-extension: yaml  #后缀名
        group: DEFAULT_GROUP      #分组
        namespace: public  #命名空间的id

#eureka:
#  client:
#    service-url:
#      defaultZone: http://114.116.106.172:7001/eureka/
#    enabled: true
#  instance:
#   prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: org.my.springcloud.base.bean
  configuration:
    map-underscore-to-camel-case: true
